server:
  port: 8081

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      database: 0
      host: 101.132.191.77
      port: 6379
      password: 123456
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
      timeout: 5000
    activemq:
      broker-url: tcp://127.0.0.1:61616
      user: admin
      password: admin
queue: kmx.pas.job.sgtest
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
########################################################
###Redis (RedisConfiguration)
########################################################

###spring.redis.database=0
###spring.redis.host=127.0.0.1
###spring.redis.port=6379
###spring.redis.password=123456
###spring.redis.pool.max-idle=8
###spring.redis.pool.min-idle=0
###spring.redis.pool.max-active=8
###spring.redis.pool.max-wait=-1
###spring.redis.timeout=5000
